name: Build and Test CI

on:
  schedule:
    # Every Thursday at 6 PM IST (12:30 PM UTC).
    - cron: '30 12 * * 4'
  workflow_dispatch:
    inputs:
      yb_version:
        description: 'YB version (e.g., 2.27.0.0-b123)'
        required: true
        type: string
        default: '2.25.2.0-b359'
      run_subset_tests:
        description: 'Run a subset of tests?'
        required: true
        type: boolean
        default: true
      test_regex:
        description: 'Regex for subset of tests (e.g., "**/com/example/MyTest*.java"). Required if run_subset_tests is true.'
        required: false
        type: string
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    env:
      YB_VERSION: ${{ inputs.yb_version || '2.25.2.0-b359' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Package from S3
        run: |
          echo "Downloading package from S3 for YB version ${{ env.YB_VERSION }}"
          curl -L https://s3.us-west-2.amazonaws.com/releases.yugabyte.com/${{ env.YB_VERSION }}/yugabyte-${{ env.YB_VERSION }}-centos-x86_64.tar.gz -o yugabytedb-${{ env.YB_VERSION }}.tar.gz
          echo "Package downloaded."
          tar -xzf yugabytedb-${{ env.YB_VERSION }}.tar.gz
      - name: Starting up YugabyteDB cluster
        run: |
          # This is to ensure that only the version number is used in the directory name.
          ls -la
          cd yugabyte-$(echo ${{ env.YB_VERSION }} | cut -d'-' -f1)
          echo "Starting up YugabyteDB cluster"
          ./bin/yugabyted start --advertise_address 127.0.0.1 --daemon true

      - name: Compile Java Code
        run: mvn clean verify -Dquick

      - name: Run All Tests
        if: ${{ (github.event_name != 'pull_request') && (github.event_name == 'workflow_dispatch' || !inputs.run_subset_tests) }}
        run: mvn clean test

      - name: Run Subset of Tests - 1
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running subset of tests with regex: ${{ inputs.test_regex }}"
          mvn test -Dtest=YugabyteDBCompleteTypesTest
      
      - name: Run Subset of Tests - 2
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBSnapshotTest"
          mvn test -Dtest=YugabyteDBSnapshotTest

      - name: Run Subset of Tests - 3
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBDatatypesTest"
          mvn test -Dtest=YugabyteDBDatatypesTest

      - name: Run Subset of Tests - 4
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBNoOpTest"
          mvn test -Dtest=YugabyteDBNoOpTest

      - name: Run Subset of Tests - 5
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBRestartTest"
          mvn test -Dtest=YugabyteDBRestartTest

      - name: Run Subset of Tests - 6
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBExplicitCheckpointingTest"
          mvn test -Dtest=YugabyteDBExplicitCheckpointingTest

      - name: Run Subset of Tests - 7
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBCQLTest"
          mvn test -Dtest=YugabyteDBCQLTest

      - name: Run Subset of Tests - 8
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBConfigTest"
          mvn test -Dtest=YugabyteDBConfigTest

      - name: Run Subset of Tests - 9
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBSnapshotResumeTest"
          mvn test -Dtest=YugabyteDBSnapshotResumeTest

      - name: Run Subset of Tests - 10
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBTransactionMetadataTest"
          mvn test -Dtest=YugabyteDBTransactionMetadataTest

      - name: Run Subset of Tests - 11
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBBeforeImageTest"
          mvn test -Dtest=YugabyteDBBeforeImageTest

      - name: Run Subset of Tests - 12
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBSchemaEvolutionTest"
          mvn test -Dtest=YugabyteDBSchemaEvolutionTest

      - name: Run Subset of Tests - 13
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBPartitionTest"
          mvn test -Dtest=YugabyteDBPartitionTest

      - name: Run Subset of Tests - 14
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBTabletSplitTest"
          mvn test -Dtest=YugabyteDBTabletSplitTest

      - name: Run Subset of Tests - 15
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBTransactionalTest"
          mvn test -Dtest=YugabyteDBTransactionalTest

      - name: Run Subset of Tests - 16
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBConsistencyWithColocatedTest"
          mvn test -Dtest=YugabyteDBConsistencyWithColocatedTest

      - name: Run Subset of Tests - 17
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBEnumValuesTest"
          mvn test -Dtest=YugabyteDBEnumValuesTest

      - name: Run Subset of Tests - 18
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBgRPCConnectorIT"
          mvn test -Dtest=YugabyteDBgRPCConnectorIT

      - name: Run Subset of Tests - 19
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBgRPCConnectorUtilsTest"
          mvn test -Dtest=YugabyteDBgRPCConnectorUtilsTest

      - name: Run Subset of Tests - 20
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBColocatedTablesTest"
          mvn test -Dtest=YugabyteDBColocatedTablesTest

      - name: Run Subset of Tests - 21
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBPublicationReplicationTest"
          mvn test -Dtest=YugabyteDBPublicationReplicationTest

      - name: Run Subset of Tests - 22
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running SourceInfoTest"
          mvn test -Dtest=SourceInfoTest

      - name: Run Subset of Tests - 23
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running ClientAPITest"
          mvn test -Dtest=ClientAPITest

      - name: Run Subset of Tests - 24
        if: ${{ inputs.run_subset_tests }} || ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: |
          echo "Running YugabyteDBStreamConsistencyTest"
          mvn test -Dtest=YugabyteDBStreamConsistencyTest

      - name: Check Test Results
        if: ${{ always() }}
        run: |
          echo "Checking test results..."
          if [ $? -ne 0 ]; then
            echo "One or more tests failed"
            exit 1
          fi
          echo "All tests completed successfully"
